### ISSUE TITLE
[BUG] (oude) gesynchroniseerde activiteiten kan ik niet aanpassen

### ISSUE THREAD

**Issue by KWillemse** [Nelos-VZW/dives-2#119]
**Beschrijf de bug**
Als ik naar mijn logboek ga kijken kan ik de theorie activiteiten van december (DIVES 1.0) nog aanpassen, ook een recente gelogde duik (in DIVES 2.0), maar activiteiten van voor december (DIVES 1.0) kan ik niet aanpassen.

**Stappen om te reproduceren**
Als ik klik op een activiteit van bv 12 december, dan heb ik een knop 'verwijderen' en 'aanpassen', voor een activiteit van bv 19 november heb ik die knoppen niet. 

**Verwachte resultaat**
Ik begrijp dat je een duik of theorieles niet mag verwijderen als er een proef aan gekoppeld is maar mag je duiken zonder proef van DIVES 1.0 ook niet verwijderen? En waarom kan ik dat dan wel voor die theorie activiteit van DIVES 1.0

**Screenshots**
Deze kan ik 'verwijderen' en 'aanpassen':
![image](https://user-images.githubusercontent.com/121305742/209387449-629e4f3a-7803-4b82-b328-c31aba87b8eb.png)

Deze kan ik niet 'verwijderen' noch 'aanpassen', en er hangt geen proef aan vast.
![image](https://user-images.githubusercontent.com/121305742/209387663-fd544dd8-8b77-4a09-9e07-72845550461c.png)

**Desktop:**
 - Besturingssysteem: Windows 10
 - Browser: Chrome
 - Versie: Version 105.0.5195.127 (Official Build) (32-bit)

**Comment by ndsmyter** [comment]
Hey @KWillemse ,
Dat is eigenlijk "by design". Een activiteit mag maximaal 14 dagen aangepast worden. Je hebt dus tijdens die 14 dagen alle vrijheid om de aanpassingen te doen die je zou willen, waaronder ook verwijderen. Maar na 14 dagen wordt deze "geblokkeerd".

Ik begrijp dat dit natuurlijk niet duidelijk was vanuit het scherm. Maar er stond wel nog op onze planning om een melding te tonen op het scherm. Ik heb dit nu beetje naar voor geschoven en deze net geïmplementeerd zoals in onderstaande screenshot.

<img width="527" alt="image" src="https://user-images.githubusercontent.com/648669/209431074-b97cad5b-5c05-49a8-a0ef-17a0f1d1e12f.png">

**Comment by KWillemse** [comment]
geverifieerd en goedgekeurd
