### ISSUE TITLE
[BUG] Er komt niet bij elke proef een einddatum

### ISSUE THREAD

**Issue by DIVEScoordinator** [Nelos-VZW/dives-2#142]
**Beschrijf de bug**
Niet bij elke proef komt een einddatum - bij het doorlopen van de brevetten pas de eerste keer gezien bij 2\*I.
Dus niet bij 1\*D tot en met 1\*I

![image](https://user-images.githubusercontent.com/112652115/213540295-52ae7a60-4495-4d50-b9f3-0510fde3fc81.png)
![image](https://user-images.githubusercontent.com/112652115/213540448-3b1db842-15c3-43b5-8897-8d886bf695e9.png)

**Comment by ndsmyter** [comment]
Dit blijkt bij nader inzien geen bug te zijn, maar eerder "by design". Het was me eerst ook nog niet opgevallen.

Maar je ziet dus geen data van proeven als je geen opleidingsverantwoordelijke bent van die persoon. Je ziet dus niet wanneer de proef afgelegd is, en bijgevolgd ook niet wanneer dat die vervalt. Je ziet enkel dat de proef "afgelegd" is. Dit om toch een beetje privacy te behouden.

De 2*I waarover je spreekt, is dus vermoedelijk iemand waar jij OPLV van bent. Of misschien gewoon iemand uit je club. Ben niet meer 100% zeker of je het ook niet gewoon mag zien als het iemand uit je club is. Kan ik wel eens uitzoeken moest dit voor jou een belangrijk verschil maken.

**Comment by DIVEScoordinator** [comment]
Ok kwestie van het juist te communiceren. Ik heb alles met DO NELOS gecheckt dus ik kijk nog grens of dat klopt met mijn account. Ik ben van niemandOPLV. Gr

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Nicolas De Smyter ***@***.***>
Verzonden: Friday, January 20, 2023 10:05:17 PM
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] [BUG] Er komt niet bij elke proef een einddatum (Issue #142)


Dit blijkt bij nader inzien geen bug te zijn, maar eerder "by design". Het was me eerst ook nog niet opgevallen.

Maar je ziet dus geen data van proeven als je geen opleidingsverantwoordelijke bent van die persoon. Je ziet dus niet wanneer de proef afgelegd is, en bijgevolgd ook niet wanneer dat die vervalt. Je ziet enkel dat de proef "afgelegd" is. Dit om toch een beetje privacy te behouden.

De 2*I waarover je spreekt, is dus vermoedelijk iemand waar jij OPLV van bent. Of misschien gewoon iemand uit je club. Ben niet meer 100% zeker of je het ook niet gewoon mag zien als het iemand uit je club is. Kan ik wel eens uitzoeken moest dit voor jou een belangrijk verschil maken.
