### ISSUE TITLE
Foutieve gegevens in tab "Opleidingen"

### ISSUE THREAD

**Issue by MarcKete** [Nelos-VZW/dives-2#397]
Via de initialisatie module de historiek (duiken tot 2019) aan de hand van het logboek ingegeven 
**3* duiker sinds 27/06/2001** 

### Gegevens in tab"Mijn Profiel

1. Heldere zeeduik: 
  [X] * aantal: 60 voor totaal van  51 u 27 min
2. Zeeduik:
  [X ] * aantal: 91 voor totaal van 73 u 29 min

### Gegevens in tab "Opleidingen > 4*D: OW-Proeven en duikleidingen

> 4 zeeduiken met helder zicht = **0% (0/4)**
> 40 duiken sinds behalen 3*D-Brevet = **(12.5% (5/40)**

### Aanduiden 3*brevet sinds:
Blijkbaar detecteert de site niet wanneer het 3* brevet gehaald werd (ik zie geen tags hiervoor), of wordt de info niet uit de brevet database opgeladen). Hierdoor kan er in de brevet module ook geen rekening gehouden worden hoeveel een bepaald soort duiken behaald werden.

in bijlage enkele voorbeelden
![Dives_proeven_4ster](https://github.com/Nelos-VZW/dives-2/assets/84070955/5a54c7ee-5809-4fb8-94e7-f972ed61cf52)
![Dives_Type_duiken](https://github.com/Nelos-VZW/dives-2/assets/84070955/5830560a-65ea-4802-a2a6-fad0f9a21e14)

**Comment by DIVEScoordinator** [comment]
@ndsmyter kan dit te maken hebben met de datum van het halen van zijn drie ster (2001)
Voor een kandidaat in mijn club werkt dat wel, zij is sinds 2006 3*D
![image](https://github.com/Nelos-VZW/dives-2/assets/112652115/8dfe0759-cc7c-4fde-936b-7eabbc18f7fe)

**Comment by ndsmyter** [comment]
Ik zie dat de tellers van op het profiel grotendeels lijken te komen vanuit de initialisatie, dus dat verklaart wel grotendeels waarom het niet volledig in sync staat.

Ik heb nu de "Heldere zeeduik" toegevoegd aan de lijst van tags die ook geteld moeten worden vanuit de initiatlisatie. Want hier is het mogelijk om de tellers mee te nemen.

Wat de teller betreft voor de 40 duiken sinds behalen van 3*D, daar kan de initialisatie niet helpen. De code weet niet wanneer dat die duiken juist gedaan zijn, want het heeft enkel de informatie van het aantal. Die duiken kunnen bijvoorbeeld ook allemaal gedaan geweest zijn toen je 2*D was. En dan mogen die niet meetellen.

Dus om die laatste af te tekenen, moet je uw boekje eens tonen aan de opleidingsverantwoordelijke, zodanig dat hij/zij dit dan via een vrijstelling kan aftekenen.

**Comment by MarcKete** [comment]
Goede middag Nicolas,Hartelijk dank om deze wijzigingen aan te brengen. Als ik me niet vergis, is dat nu inderdaad in orde in de opleidingsmodule.Wat betreft die 40 duiken,  zou dit al niet deels op te lossen zijn door een nieuw velden aan de db toe te voegen, waarin je kan aanduiden wanneer je welk brevet behaald hebt? Vermoedelijk is deze info reeds gekend waardoor het enkel maar kwestie is van dit zichtbaar (read only) te maken.Eventueel wil wel een xls doorsturen waarin de voorgaande duiken staan opgelijst (inclusief datum).Dank alvast voor je hulp hierin Vriendelijke groeten,Marc KetelsSent by mobile device
-------- Oorspronkelijk bericht --------Van: Nicolas De Smyter ***@***.***> Datum: 19/03/2024  15:40  (GMT+01:00) Aan: Nelos-VZW/dives-2 ***@***.***> Cc: MarcKete ***@***.***>, Author ***@***.***> Onderwerp: Re: [Nelos-VZW/dives-2] Foutieve gegevens in tab "Opleidingen" (Issue
  #397) 
Ik zie dat de tellers van op het profiel grotendeels lijken te komen vanuit de initialisatie, dus dat verklaart wel grotendeels waarom het niet volledig in sync staat.
Ik heb nu de "Heldere zeeduik" toegevoegd aan de lijst van tags die ook geteld moeten worden vanuit de initiatlisatie. Want hier is het mogelijk om de tellers mee te nemen.
Wat de teller betreft voor de 40 duiken sinds behalen van 3D, daar kan de initialisatie niet helpen. De code weet niet wanneer dat die duiken juist gedaan zijn, want het heeft enkel de informatie van het aantal. Die duiken kunnen bijvoorbeeld ook allemaal gedaan geweest zijn toen je 2D was. En dan mogen die niet meetellen.
Dus om die laatste af te tekenen, moet je uw boekje eens tonen aan de opleidingsverantwoordelijke, zodanig dat hij/zij dit dan via een vrijstelling kan aftekenen.

**Comment by DIVEScoordinator** [comment]
Marc

Zoals gisteren besproken is bewust gekozen om in de tweede versie geen mogelijkheid maar te voorzien voor intialisatie van aantal duiken sinds 3*D omdat ondertussen de meesten die info toch al in het systeem hebben staan.  Voor u specifiek geval lossen ze dat volgende week manueel op.



Met vriendelijke groeten

***@***.***
Lutgart Stals
NELOS - CMAS 3*Instructeur
Lid van het NELOS-Bestuur | Medecoördinator DIVES
Website: www.nelos.be<http://www.nelos.be/>

Mobile: +32 492 23 07 06 | e-mail: ***@***.******@***.***>
________________________________
Nederlandstalige Liga voor Onderwateronderzoek en -Sport vzw (NELOS vzw)
Brusselsesteenweg 313-315, 2800 Mechelen, België | Tel.: +32 15 29 04 86
Ondernemingsnr.: RPR 0418.461.463


Van: MarcKete ***@***.***>
Verzonden: woensdag 20 maart 2024 13:25
Aan: Nelos-VZW/dives-2 ***@***.***>
CC: Lutgart Stals ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Nelos-VZW/dives-2] Foutieve gegevens in tab "Opleidingen" (Issue #397)

Goede middag Nicolas,Hartelijk dank om deze wijzigingen aan te brengen. Als ik me niet vergis, is dat nu inderdaad in orde in de opleidingsmodule.Wat betreft die 40 duiken,  zou dit al niet deels op te lossen zijn door een nieuw velden aan de db toe te voegen, waarin je kan aanduiden wanneer je welk brevet behaald hebt? Vermoedelijk is deze info reeds gekend waardoor het enkel maar kwestie is van dit zichtbaar (read only) te maken.Eventueel wil wel een xls doorsturen waarin de voorgaande duiken staan opgelijst (inclusief datum).Dank alvast voor je hulp hierin Vriendelijke groeten,Marc KetelsSent by mobile device
-------- Oorspronkelijk bericht --------Van: Nicolas De Smyter ***@***.***> Datum: 19/03/2024 15:40 (GMT+01:00) Aan: Nelos-VZW/dives-2 ***@***.***> Cc: MarcKete ***@***.***>, Author ***@***.***> Onderwerp: Re: [Nelos-VZW/dives-2] Foutieve gegevens in tab "Opleidingen" (Issue
#397)
Ik zie dat de tellers van op het profiel grotendeels lijken te komen vanuit de initialisatie, dus dat verklaart wel grotendeels waarom het niet volledig in sync staat.
Ik heb nu de "Heldere zeeduik" toegevoegd aan de lijst van tags die ook geteld moeten worden vanuit de initiatlisatie. Want hier is het mogelijk om de tellers mee te nemen.
Wat de teller betreft voor de 40 duiken sinds behalen van 3D, daar kan de initialisatie niet helpen. De code weet niet wanneer dat die duiken juist gedaan zijn, want het heeft enkel de informatie van het aantal. Die duiken kunnen bijvoorbeeld ook allemaal gedaan geweest zijn toen je 2D was. En dan mogen die niet meetellen.
Dus om die laatste af te tekenen, moet je uw boekje eens tonen aan de opleidingsverantwoordelijke, zodanig dat hij/zij dit dan via een vrijstelling kan aftekenen.

-Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>


-
